### ISSUE TITLE
sol2uml storage: `Failed to generate storage diagram`, while uml diagram generates without error

### ISSUE THREAD

**Issue by gpersoon** [naddison36/sol2uml#89] opened 2022-08-05 08:50 UTC
sol2uml storage shows this error: `Failed to generate storage diagram`, 
while the uml diagram generates without error, as well as `sol2uml flatten`.
Note: the `@openzeppelin` contracts are not installed locally.

`>sol2uml 0x2762e676a9f17c7de34fe4b124424837c7e18e1c`
Generated svg file KoiosECDSA.svg

`>sol2uml flatten 0x2762e676a9f17c7de34fe4b124424837c7e18e1c`
Solidity written to KoiosECDSA.sol

`>sol2uml storage 0x2762e676a9f17c7de34fe4b124424837c7e18e1c`
Failed to generate storage diagram.
Error: Failed to find inherited contract "ERC721" of "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol"
    at C:\Users\...\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:70:19
    at Array.forEach (<anonymous>)
    at parseVariables (C:\Users\...\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:67:27)
    at C:\Users\...\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:73:9
    at Array.forEach (<anonymous>)
    at parseVariables (C:\Users\...\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:67:27)
    at convertClasses2Storages (C:\Users\...\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:41:23)
    at Command.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\sol2uml\lib\sol2uml.js:118:81)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.parseAsync (C:\Users\...\AppData\Roaming\npm\node_modules\sol2uml\node_modules\commander\lib\command.js:917:5)

**Comment by naddison36** [comment] 2022-08-06 22:00
This is strange. I can tell from the error message that you are using at least v2.1.1 which works for me. If you were using an older version I'd say try upgrading to the latest release but I don't think that's going to help here.

```
sol2uml storage 0x2762e676a9f17c7de34fe4b124424837c7e18e1c   
Generated svg file /Users/nicholasaddison/KoiosECDSA.svg
```
![KoiosECDSA](https://user-images.githubusercontent.com/6491112/183267301-450a14a1-7de5-4d51-802f-7c899b5a3f3b.svg)

What operating system and node version are you using?

**Comment by gpersoon** [comment] 2022-08-08 09:48
I'm using Windows 11 (Version 10.0.22000.832) and Node version 18.7.0:

```js
>sol2uml storage 0x2762e676a9f17c7de34fe4b124424837c7e18e1c -v
  sol2uml verbose on +0ms
  sol2uml argument 0x2762e676a9f17c7de34fe4b124424837c7e18e1c is an Ethereum address so checking Etherscan for the verified source code +0ms
  sol2uml About to get Solidity source code for 0x2762e676a9f17c7de34fe4b124424837c7e18e1c from https://api.etherscan.io/api +0ms
  sol2uml Adding contract KoiosECDSA +0ms
  sol2uml Adding contract SignedTokenVerifier +19ms
  sol2uml Adding contract ECDSA +57ms
  sol2uml Adding contract IERC721Enumerable +2ms
  sol2uml Adding contract ERC721Enumerable +36ms
  sol2uml Adding contract Strings +19ms
  sol2uml Adding contract Ownable +8ms
  sol2uml Adding contract IERC721 +2ms
  sol2uml Adding contract ERC721 +59ms
  sol2uml Adding contract Context +2ms
  sol2uml Adding contract IERC165 +0ms
  sol2uml Adding contract ERC165 +1ms
  sol2uml Adding contract Address +16ms
  sol2uml Adding contract IERC721Metadata +1ms
  sol2uml Adding contract IERC721Receiver +1ms
Failed to generate storage diagram.
Error: Failed to find inherited contract "ERC721" of "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol"
    at C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:70:19
    at Array.forEach (<anonymous>)
    at parseVariables (C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:67:27)
    at C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:73:9
    at Array.forEach (<anonymous>)
    at parseVariables (C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:67:27)
    at convertClasses2Storages (C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:41:23)
    at Command.<anonymous> (C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\lib\sol2uml.js:118:81)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\node_modules\commander\lib\command.js:917:5)
```

```js
>sol2uml flatten 0x2762e676a9f17c7de34fe4b124424837c7e18e1c
Solidity written to KoiosECDSA.sol
```
When I try it based on `KoiosECDSA.sol`, I get: `Error: Failed to find contract with name "undefined"`
```js
>sol2uml storage KoiosECDSA.sol -v
  sol2uml verbose on +0ms
  sol2uml About to get Solidity files under KoiosECDSA.sol +0ms
  sol2uml Got Solidity file to be parsed: KoiosECDSA.sol +0ms
  sol2uml Adding contract ERC721Enumerable +0ms
  sol2uml Adding contract Ownable +2ms
  sol2uml Adding contract Strings +0ms
  sol2uml Adding contract KoiosECDSA +0ms
  sol2uml Adding contract ECDSA +0ms
  sol2uml Adding contract SignedTokenVerifier +1ms
  sol2uml Adding contract IERC721Enumerable +0ms
  sol2uml Adding contract IERC721 +0ms
  sol2uml Adding contract ERC721 +0ms
  sol2uml Adding contract Context +1ms
  sol2uml Adding contract IERC165 +0ms
  sol2uml Adding contract ERC165 +0ms
  sol2uml Adding contract Address +0ms
  sol2uml Adding contract IERC721Metadata +0ms
  sol2uml Adding contract IERC721Receiver +0ms
Failed to generate storage diagram.
Error: Failed to find contract with name "undefined"
    at convertClasses2Storages (C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\lib\converterClasses2Storage.js:38:15)
    at Command.<anonymous> (C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\lib\sol2uml.js:118:81)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\node_modules\commander\lib\command.js:917:5)
    at async main (C:\Users\gerar\AppData\Roaming\npm\node_modules\sol2uml\lib\sol2uml.js:181:5)
``` 

I've also tried it on `Ubuntu 20.04.4 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)`, with node v16.15.1:

First time:
```js
 sol2uml storage 0x2762e676a9f17c7de34fe4b124424837c7e18e1c -v
  sol2uml verbose on +0ms
  sol2uml argument 0x2762e676a9f17c7de34fe4b124424837c7e18e1c is an Ethereum address so checking Etherscan for the verified source code +0ms
  sol2uml About to get Solidity source code for 0x2762e676a9f17c7de34fe4b124424837c7e18e1c from https://api.etherscan.io/api +0ms
undefined
```

Second time it worked though!:
```js
sol2uml storage 0x2762e676a9f17c7de34fe4b124424837c7e18e1c
  ...
Generated svg file /home/gerard/uml/KoiosECDSA.svg
```

However this gives an error:
```js
sol2uml storage KoiosECDSA.sol -v
  sol2uml verbose on +0ms
  sol2uml About to get Solidity files under KoiosECDSA.sol +0ms
  sol2uml Got Solidity file to be parsed: KoiosECDSA.sol +0ms
  sol2uml Adding contract Context +0ms
  sol2uml Adding contract IERC165 +1ms
  sol2uml Adding contract ERC165 +0ms
  sol2uml Adding contract IERC721 +0ms
  sol2uml Adding contract IERC721Metadata +0ms
  sol2uml Adding contract Address +0ms
  sol2uml Adding contract Strings +1ms
  sol2uml Adding contract ERC721 +0ms
  sol2uml Adding contract IERC721Enumerable +1ms
  sol2uml Adding contract ERC721Enumerable +0ms
  sol2uml Adding contract Ownable +0ms
  sol2uml Adding contract ECDSA +0ms
  sol2uml Adding contract SignedTokenVerifier +0ms
  sol2uml Adding contract KoiosECDSA +0ms
  sol2uml Adding contract IERC721Receiver +1ms
Error: Failed to find contract with name "undefined"
    at convertClasses2Storages (/home/gerard/.nvm/versions/node/v16.15.1/lib/node_modules/sol2uml/lib/converterClasses2Storage.js:38:15)
    at Command.<anonymous> (/home/gerard/.nvm/versions/node/v16.15.1/lib/node_modules/sol2uml/lib/sol2uml.js:113:81)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.parseAsync (/home/gerard/.nvm/versions/node/v16.15.1/lib/node_modules/sol2uml/node_modules/commander/lib/command.js:917:5)
    at async main (/home/gerard/.nvm/versions/node/v16.15.1/lib/node_modules/sol2uml/lib/sol2uml.js:178:5)
```

**Comment by naddison36** [comment] 2022-08-09 01:41
Thanks for this information. That's super useful. I'll have to debug on a Windows machine so the import paths logic will work on Mac/Linux and Windows.

**Comment by naddison36** [comment] 2022-08-14 05:32
This should be fixed with v2.1.6.

The problem was I needed to use the `posix` resolve when working with imports from files sourced from Etherscan. When running on windows, `path` defaults to `win32` which will not work.

**Closed by naddison36** 2022-08-14 05:32 UTC

**Comment by zguesmi** [comment] 2023-10-27 09:32
Hi @naddison36 ,
I am having the same issue when trying to generate storage diagram for a contract in local folder.
First, do you confirm that it is possible to that or it only works with deployed contracts?

**Comment by naddison36** [comment] 2023-10-27 10:38
storage diagrams should work with local contracts. Are you on Windows?

**Comment by naddison36** [comment] 2023-10-27 21:58
Is the code open source? Can I look at the Solidity source files?

My guess is the code is importing from an import which sol2uml currently doesn't handle. It's on my TODO list when I get time. The workaround is to import `<problematicContract>` directly to `<mainContract>.sol`

**Comment by zguesmi** [comment] 2023-10-30 15:05
I will try to prepare something that reproduces the issue.

**Comment by zguesmi** [comment] 2023-10-30 17:04
@naddison36 
Please check this repo, you can reproduce the issue there.
https://github.com/zguesmi/storage-diagrams#sol2uml
As instructed in the README, install npm packages and run
```
npx sol2uml storage -c Store contracts/
```
you should get the error
```
Error: Failed to find inherited contract "Ownable" of ".../contracts/Store.sol"
```
BTW, `sol2uml class ...` command is working fine.

**Comment by rori4** [comment] 2023-11-10 15:22
> @naddison36 Please check this repo, you can reproduce the issue there. https://github.com/zguesmi/storage-diagrams#sol2uml As instructed in the README, install npm packages and run
> 
> ```
> npx sol2uml storage -c Store contracts/
> ```
> 
> you should get the error
> 
> ```
> Error: Failed to find inherited contract "Ownable" of ".../contracts/Store.sol"
> ```
> 
> BTW, `sol2uml class ...` command is working fine.

@naddison36 I am having the exact same issue. Any workaround for this?

**Comment by naddison36** [comment] 2023-11-11 02:41
> @naddison36 Please check this repo, you can reproduce the issue there. https://github.com/zguesmi/storage-diagrams#sol2uml As instructed in the README, install npm packages and run
> 
> ```
> npx sol2uml storage -c Store contracts/
> ```
> 
> you should get the error
> 
> ```
> Error: Failed to find inherited contract "Ownable" of ".../contracts/Store.sol"
> ```
> 
> BTW, `sol2uml class ...` command is working fine.

Apologies for the delay.

So the problem is `sol2uml` will only look for contracts under the folder you specify. So in the above example, it's looking for contracts under the `contracts` folder. The `Ownable` contract is under `./node_modules/@openzeppelin/contracts/access/`

You can pass in a comma-separated list of folders so all of the following will work

```
sol2uml storage -c Store .
sol2uml storage -c Store contracts/,./node_modules
sol2uml storage -c Store contracts/,./node_modules/@openzeppelin/contracts/ 
```

**Comment by zguesmi** [comment] 2023-11-27 09:43
Thank you @naddison36 for your answer!
It's clearer to me now.

**Comment by zguesmi** [comment] 2023-11-30 10:46
I confirm that your recommendation fixed my issue.
I also fixed the next issue using this comment https://github.com/naddison36/sol2uml/issues/175#issuecomment-1807445743.
Thank you @naddison36.
